#!/usr/bin/env node
// SETUP_WIZARD_V1 — interactive installer that generates .env
// Usage:  node setup.js        (or: npm run setup)
// No external dependencies: only Node.js built-ins.

const fs       = require('fs');
const path     = require('path');
const net      = require('net');
const readline = require('readline');

const ENV_PATH = path.join(__dirname, '.env');

// ─────────────────────────────────────────────────────────────
//  i18n — UI strings and .env comments per language
// ─────────────────────────────────────────────────────────────
const L = {
    en: {
        name: 'English',
        title: 'Discord RCON Bot + Web Panel — setup wizard',
        hintSkip: 'Press Enter to accept the value in [brackets]. Type "-" to leave empty.',
        secExists: 'A .env file already exists.',
        askOverwrite: 'Overwrite it? (current values are offered as defaults)',
        aborted: 'Cancelled. Nothing was written.',
        secDiscord: 'DISCORD',
        secPerms: 'PERMISSIONS',
        secRcon: 'RCON (Minecraft server)',
        secWeb: 'WEB PANEL',
        qToken: 'Bot token (Developer Portal -> Bot -> Reset Token). Empty = run web panel only',
        qClient: 'Application ID (Developer Portal -> General Information -> Application ID)',
        qGuild: 'Server ID (Developer Mode on -> right-click server -> Copy Server ID)',
        qAdminRole: 'Admin ROLE ID (right-click role -> Copy Role ID). Empty = no role check',
        qChannel: 'Command channel ID (right-click channel -> Copy Channel ID). Empty = any channel',
        qRconHost: 'Minecraft server address',
        qRconPort: 'RCON port (server.properties -> rcon.port)',
        qRconPass: 'RCON password (server.properties -> rcon.password)',
        qRconTimeout: 'RCON timeout, ms',
        qWebEnabled: 'Enable the web panel?',
        qWebPort: 'Web panel port (always bound to 127.0.0.1)',
        qWebPass: 'Web panel password',
        qWebRootPass: 'Root password for privileged actions. Empty = disabled',
        qWebTtl: 'Session lifetime, minutes',
        qTestRcon: 'Test the RCON port now?',
        testOk: 'Port is reachable.',
        testFail: 'Could not reach the port:',
        testHint: 'Check that the server is running and server.properties has enable-rcon=true.',
        warnNoPass: 'Warning: the web panel is enabled without a password — anyone with local access can use it.',
        badPort: 'Enter a number between 1 and 65535.',
        badId: 'A Discord ID is 17-20 digits. Try again or leave it empty with "-".',
        badNum: 'Enter a positive number.',
        yes: 'y', no: 'n',
        summary: 'Summary',
        askWrite: 'Write these values to .env?',
        written: 'Saved:',
        next: 'Next steps:',
        next1: 'npm install                 — install dependencies',
        next2: 'node deploy-commands.js     — register slash commands (needs token + IDs)',
        next3: 'npm start                   — run the bot and/or web panel',
        next4: 'Web panel: http://127.0.0.1:',
        hdr: {
            file: 'Generated by setup.js. Do not commit this file.',
            discord: 'DISCORD',
            token: 'Bot token. Developer Portal -> your application -> Bot -> Reset Token. Keep it secret.',
            client: 'Application (bot) ID, not your user ID. Used to register slash commands.',
            guild: 'Your Discord server ID ("guild" = server). Commands are registered for this server only.',
            perms: 'PERMISSIONS',
            role: 'ID of the ROLE allowed to run commands (not a user). Empty = no role check.',
            chan: 'Channel where the bot accepts commands. Empty = any channel.',
            rcon: 'RCON — connection to the Minecraft server (server.properties: enable-rcon=true)',
            host: 'Server address. 127.0.0.1 if the bot runs on the same machine.',
            port: 'RCON port, from server.properties -> rcon.port.',
            pass: 'RCON password, must match server.properties -> rcon.password.',
            timeout: 'How long to wait for an RCON reply, in milliseconds.',
            web: 'WEB PANEL — shows Connected / Players online / Whitelist / WS ping',
            webNote: 'Always listens on 127.0.0.1. Remote access: ssh -L 3000:127.0.0.1:3000 user@host',
            webEnabled: 'Start the web panel with the bot. Any value except "false" = enabled.',
            webPort: 'Panel port. Open http://127.0.0.1:<port>',
            webPass: 'Login password for the panel. Empty = no password (not recommended).',
            webRoot: 'Second password for privileged (root) actions. Empty = disabled.',
            webTtl: 'Session lifetime in minutes after login (720 = 12 hours).',
        },
    },
    ru: {
        name: 'Русский',
        title: 'Discord RCON бот + веб-панель — мастер установки',
        hintSkip: 'Enter — оставить значение в [скобках]. Введите "-", чтобы оставить пустым.',
        secExists: 'Файл .env уже существует.',
        askOverwrite: 'Перезаписать его? (текущие значения будут предложены по умолчанию)',
        aborted: 'Отменено. Ничего не записано.',
        secDiscord: 'DISCORD',
        secPerms: 'ПРАВА ДОСТУПА',
        secRcon: 'RCON (сервер Minecraft)',
        secWeb: 'ВЕБ-ПАНЕЛЬ',
        qToken: 'Токен бота (Developer Portal -> Bot -> Reset Token). Пусто = только веб-панель',
        qClient: 'Application ID приложения (Developer Portal -> General Information)',
        qGuild: 'ID сервера (включите Режим разработчика -> ПКМ по серверу -> Копировать ID)',
        qAdminRole: 'ID РОЛИ админов (ПКМ по роли -> Копировать ID роли). Пусто = без проверки роли',
        qChannel: 'ID канала для команд (ПКМ по каналу -> Копировать ID). Пусто = любой канал',
        qRconHost: 'Адрес сервера Minecraft',
        qRconPort: 'Порт RCON (server.properties -> rcon.port)',
        qRconPass: 'Пароль RCON (server.properties -> rcon.password)',
        qRconTimeout: 'Таймаут RCON, мс',
        qWebEnabled: 'Включить веб-панель?',
        qWebPort: 'Порт веб-панели (всегда слушает 127.0.0.1)',
        qWebPass: 'Пароль веб-панели',
        qWebRootPass: 'Рут-пароль для привилегированных действий. Пусто = выключено',
        qWebTtl: 'Время жизни сессии, минут',
        qTestRcon: 'Проверить доступность порта RCON сейчас?',
        testOk: 'Порт доступен.',
        testFail: 'Порт недоступен:',
        testHint: 'Проверьте, что сервер запущен и в server.properties указано enable-rcon=true.',
        warnNoPass: 'Внимание: панель включена без пароля — доступ получит любой, у кого есть локальный доступ.',
        badPort: 'Введите число от 1 до 65535.',
        badId: 'ID в Discord — это 17-20 цифр. Повторите или оставьте пустым через "-".',
        badNum: 'Введите положительное число.',
        yes: 'д', no: 'н',
        summary: 'Итог',
        askWrite: 'Записать эти значения в .env?',
        written: 'Сохранено:',
        next: 'Дальше:',
        next1: 'npm install                 — установить зависимости',
        next2: 'node deploy-commands.js     — зарегистрировать слэш-команды (нужны токен и ID)',
        next3: 'npm start                   — запустить бота и/или веб-панель',
        next4: 'Веб-панель: http://127.0.0.1:',
        hdr: {
            file: 'Сгенерировано setup.js. Не коммитьте этот файл.',
            discord: 'DISCORD',
            token: 'Токен бота. Developer Portal -> ваше приложение -> Bot -> Reset Token. Не показывать никому.',
            client: 'Application ID приложения (не ваш аккаунт). Нужен для регистрации слэш-команд.',
            guild: 'ID вашего Discord-сервера ("guild" = сервер). Команды ставятся только на него.',
            perms: 'ПРАВА ДОСТУПА',
            role: 'ID РОЛИ, которой разрешены команды (не пользователя). Пусто = без проверки роли.',
            chan: 'Канал, где бот принимает команды. Пусто = любой канал.',
            rcon: 'RCON — связь с сервером Minecraft (в server.properties нужно enable-rcon=true)',
            host: 'Адрес сервера. 127.0.0.1, если бот на той же машине.',
            port: 'Порт RCON из server.properties -> rcon.port.',
            pass: 'Пароль RCON, должен совпадать с server.properties -> rcon.password.',
            timeout: 'Сколько ждать ответ RCON, в миллисекундах.',
            web: 'ВЕБ-ПАНЕЛЬ — показывает Подключено / Игроки онлайн / Whitelist / Пинг WS',
            webNote: 'Всегда слушает 127.0.0.1. Удалённый доступ: ssh -L 3000:127.0.0.1:3000 user@host',
            webEnabled: 'Запускать панель вместе с ботом. Любое значение кроме "false" = включено.',
            webPort: 'Порт панели. Открывать http://127.0.0.1:<порт>',
            webPass: 'Пароль для входа в панель. Пусто = без пароля (не рекомендуется).',
            webRoot: 'Второй пароль для привилегированных (рут) действий. Пусто = выключено.',
            webTtl: 'Время жизни сессии в минутах после входа (720 = 12 часов).',
        },
    },
};

// ─────────────────────────────────────────────────────────────
//  Console helpers
// ─────────────────────────────────────────────────────────────
const C = process.stdout.isTTY
    ? { d: '\x1b[2m', b: '\x1b[1m', g: '\x1b[32m', y: '\x1b[33m', r: '\x1b[31m', c: '\x1b[36m', x: '\x1b[0m' }
    : { d: '', b: '', g: '', y: '', r: '', c: '', x: '' };

// Line reader that works both in a terminal and with piped input
// (e.g. `printf '...' | node setup.js` for unattended installs).
const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
    terminal: Boolean(process.stdin.isTTY),
});
const _lines = [];
const _waiters = [];
let _closed = false;
rl.on('line', (l) => {
    const w = _waiters.shift();
    if (w) w(l); else _lines.push(l);
});
rl.on('close', () => {
    _closed = true;
    while (_waiters.length) _waiters.shift()('');
});
function ask(q) {
    process.stdout.write(q);
    if (_lines.length) {
        const l = _lines.shift();
        if (!process.stdin.isTTY) process.stdout.write(l + '\n');
        return Promise.resolve(l);
    }
    if (_closed) { process.stdout.write('\n'); return Promise.resolve(''); }
    return new Promise((res) => _waiters.push(res));
}
const noMoreInput = () => _closed && _lines.length === 0;

function section(t) {
    console.log('\n' + C.b + C.c + '── ' + t + ' ' + '─'.repeat(Math.max(0, 60 - t.length)) + C.x);
}

// text question with default, validation and "-" = empty
async function askText(label, def, validate) {
    for (let attempt = 0; ; attempt++) {
        if (attempt > 0 && noMoreInput()) return def || '';
        const shown = def ? ' [' + def + ']' : ' []';
        const raw = (await ask(C.b + '? ' + C.x + label + C.d + shown + C.x + ': ')).trim();
        let val = raw === '' ? (def || '') : raw;
        if (raw === '-') val = '';
        if (validate) {
            const err = validate(val);
            if (err) { console.log('  ' + C.r + err + C.x); continue; }
        }
        return val;
    }
}

async function askYesNo(label, def, lang) {
    const t = L[lang];
    const hint = def ? `${t.yes.toUpperCase()}/${t.no}` : `${t.yes}/${t.no.toUpperCase()}`;
    for (let attempt = 0; ; attempt++) {
        if (attempt > 0 && noMoreInput()) return def;
        const raw = (await ask(C.b + '? ' + C.x + label + C.d + ' [' + hint + ']' + C.x + ': ')).trim().toLowerCase();
        if (raw === '') return def;
        if (['y', 'yes', 'д', 'да', '1', 'true'].includes(raw)) return true;
        if (['n', 'no', 'н', 'нет', '0', 'false'].includes(raw)) return false;
    }
}

// ─────────────────────────────────────────────────────────────
//  Validators
// ─────────────────────────────────────────────────────────────
const vDiscordId = (t) => (v) => (v === '' || /^\d{17,20}$/.test(v) ? null : t.badId);
const vPort = (t) => (v) => {
    const n = Number(v);
    return Number.isInteger(n) && n >= 1 && n <= 65535 ? null : t.badPort;
};
const vPosNum = (t) => (v) => (Number(v) > 0 ? null : t.badNum);

// ─────────────────────────────────────────────────────────────
//  Existing .env parsing (used as defaults)
// ─────────────────────────────────────────────────────────────
function readEnv(file) {
    const out = {};
    if (!fs.existsSync(file)) return out;
    for (const line of fs.readFileSync(file, 'utf8').split(/\r?\n/)) {
        const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)$/);
        if (m) out[m[1]] = m[2].trim();
    }
    return out;
}

// TCP reachability check for the RCON port
function probeTcp(host, port, timeout = 3000) {
    return new Promise((resolve) => {
        const s = new net.Socket();
        const done = (ok, err) => { s.destroy(); resolve({ ok, err }); };
        s.setTimeout(timeout);
        s.once('connect', () => done(true));
        s.once('timeout', () => done(false, 'timeout'));
        s.once('error', (e) => done(false, e.message));
        s.connect(port, host);
    });
}

// ─────────────────────────────────────────────────────────────
//  .env rendering (comments follow the chosen language)
// ─────────────────────────────────────────────────────────────
function renderEnv(v, lang) {
    const h = L[lang].hdr;
    const line = '# ' + '='.repeat(75);
    return [
        line,
        '#  ' + h.file,
        line,
        '',
        '# --- ' + h.discord + ' ---',
        '# ' + h.token,
        'DISCORD_TOKEN=' + v.DISCORD_TOKEN,
        '# ' + h.client,
        'CLIENT_ID=' + v.CLIENT_ID,
        '# ' + h.guild,
        'GUILD_ID=' + v.GUILD_ID,
        '',
        '# --- ' + h.perms + ' ---',
        '# ' + h.role,
        'ADMIN_ROLE_ID=' + v.ADMIN_ROLE_ID,
        '# ' + h.chan,
        'COMMAND_CHANNEL_ID=' + v.COMMAND_CHANNEL_ID,
        '',
        '# --- ' + h.rcon + ' ---',
        '# ' + h.host,
        'RCON_HOST=' + v.RCON_HOST,
        '# ' + h.port,
        'RCON_PORT=' + v.RCON_PORT,
        '# ' + h.pass,
        'RCON_PASSWORD=' + v.RCON_PASSWORD,
        '# ' + h.timeout,
        'RCON_TIMEOUT_MS=' + v.RCON_TIMEOUT_MS,
        '',
        '# --- ' + h.web + ' ---',
        '# ' + h.webNote,
        '# ' + h.webEnabled,
        'WEB_ENABLED=' + v.WEB_ENABLED,
        '# ' + h.webPort,
        'WEB_PORT=' + v.WEB_PORT,
        '# ' + h.webPass,
        'WEB_PASSWORD=' + v.WEB_PASSWORD,
        '# ' + h.webRoot,
        'WEB_ROOT_PASSWORD=' + v.WEB_ROOT_PASSWORD,
        '# ' + h.webTtl,
        'WEB_SESSION_TTL_MIN=' + v.WEB_SESSION_TTL_MIN,
        '',
    ].join('\n');
}

const mask = (s) => (s ? s.slice(0, 3) + '*'.repeat(Math.max(3, s.length - 3)) : '');

// ─────────────────────────────────────────────────────────────
//  Main
// ─────────────────────────────────────────────────────────────
(async function main() {
    // 1) language first — everything after this follows it
    console.log('\n' + C.b + 'Language / Язык' + C.x);
    console.log('  1) English');
    console.log('  2) Русский');
    let lang = 'en';
    for (let attempt = 0; ; attempt++) {
        if (attempt > 0 && noMoreInput()) break;
        const a = (await ask(C.b + '? ' + C.x + 'Select [1]: ')).trim();
        if (a === '' || a === '1' || /^en/i.test(a)) { lang = 'en'; break; }
        if (a === '2' || /^(ru|рус)/i.test(a)) { lang = 'ru'; break; }
    }
    const t = L[lang];

    console.log('\n' + C.b + t.title + C.x);
    console.log(C.d + t.hintSkip + C.x);

    const old = readEnv(ENV_PATH);
    if (Object.keys(old).length) {
        console.log('\n' + C.y + t.secExists + C.x);
        if (!(await askYesNo(t.askOverwrite, true, lang))) {
            console.log(t.aborted);
            rl.close();
            return;
        }
    }

    const v = {};

    section(t.secDiscord);
    v.DISCORD_TOKEN = await askText(t.qToken, old.DISCORD_TOKEN || '');
    v.CLIENT_ID     = await askText(t.qClient, old.CLIENT_ID || '', vDiscordId(t));
    v.GUILD_ID      = await askText(t.qGuild, old.GUILD_ID || '', vDiscordId(t));

    section(t.secPerms);
    v.ADMIN_ROLE_ID      = await askText(t.qAdminRole, old.ADMIN_ROLE_ID || '', vDiscordId(t));
    v.COMMAND_CHANNEL_ID = await askText(t.qChannel, old.COMMAND_CHANNEL_ID || '', vDiscordId(t));

    section(t.secRcon);
    v.RCON_HOST       = await askText(t.qRconHost, old.RCON_HOST || '127.0.0.1');
    v.RCON_PORT       = await askText(t.qRconPort, old.RCON_PORT || '25575', vPort(t));
    v.RCON_PASSWORD   = await askText(t.qRconPass, old.RCON_PASSWORD || '');
    v.RCON_TIMEOUT_MS = await askText(t.qRconTimeout, old.RCON_TIMEOUT_MS || '10000', vPosNum(t));

    if (await askYesNo(t.qTestRcon, true, lang)) {
        const r = await probeTcp(v.RCON_HOST, Number(v.RCON_PORT));
        if (r.ok) console.log('  ' + C.g + t.testOk + C.x);
        else {
            console.log('  ' + C.r + t.testFail + ' ' + r.err + C.x);
            console.log('  ' + C.d + t.testHint + C.x);
        }
    }

    section(t.secWeb);
    const webOn = await askYesNo(t.qWebEnabled, (old.WEB_ENABLED || 'true') !== 'false', lang);
    v.WEB_ENABLED = webOn ? 'true' : 'false';
    if (webOn) {
        v.WEB_PORT            = await askText(t.qWebPort, old.WEB_PORT || '3000', vPort(t));
        v.WEB_PASSWORD        = await askText(t.qWebPass, old.WEB_PASSWORD || '');
        v.WEB_ROOT_PASSWORD   = await askText(t.qWebRootPass, old.WEB_ROOT_PASSWORD || '');
        v.WEB_SESSION_TTL_MIN = await askText(t.qWebTtl, old.WEB_SESSION_TTL_MIN || '720', vPosNum(t));
        if (!v.WEB_PASSWORD && !v.WEB_ROOT_PASSWORD) console.log('  ' + C.y + t.warnNoPass + C.x);
    } else {
        v.WEB_PORT            = old.WEB_PORT || '3000';
        v.WEB_PASSWORD        = old.WEB_PASSWORD || '';
        v.WEB_ROOT_PASSWORD   = old.WEB_ROOT_PASSWORD || '';
        v.WEB_SESSION_TTL_MIN = old.WEB_SESSION_TTL_MIN || '720';
    }

    section(t.summary);
    for (const [k, val] of Object.entries(v)) {
        const shown = /TOKEN|PASSWORD/.test(k) ? mask(val) : val;
        console.log('  ' + k.padEnd(20) + '= ' + (shown || C.d + '(empty)' + C.x));
    }

    if (!(await askYesNo('\n' + t.askWrite, true, lang))) {
        console.log(t.aborted);
        rl.close();
        return;
    }

    if (fs.existsSync(ENV_PATH)) {
        fs.copyFileSync(ENV_PATH, ENV_PATH + '.bak');
    }
    fs.writeFileSync(ENV_PATH, renderEnv(v, lang), 'utf8');
    try { fs.chmodSync(ENV_PATH, 0o600); } catch (_) {}

    console.log('\n' + C.g + t.written + C.x + ' ' + ENV_PATH);
    console.log('\n' + C.b + t.next + C.x);
    console.log('  1) ' + t.next1);
    console.log('  2) ' + t.next2);
    console.log('  3) ' + t.next3);
    if (webOn) console.log('  4) ' + t.next4 + v.WEB_PORT);
    rl.close();
})().catch((e) => {
    console.error(e);
    rl.close();
    process.exit(1);
});
